FROM node:20

WORKDIR /app

# Copy package files and install
COPY package.json ./
RUN npm install && npm install ts-node typescript --save-dev

# Copy project files
COPY . .

EXPOSE 9000

CMD ["sh", "-c", "npx medusa db:migrate && npx medusa develop"]
